repos:
  - repo: 'https://github.com/astral-sh/ruff-pre-commit'
    rev: v0.1.4
    hooks:
      - id: ruff
        args: ['--fix']
  - repo: 'https://github.com/astral-sh/ruff-pre-commit'
    rev: v0.1.4
    hooks:
      - id: ruff-format
  - repo: 'https://github.com/python-poetry/poetry'
    rev: '1.7.0'
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
        args: ['-f', 'requirements.txt', '--without-hashes', '--with', 'dev', '--output', 'requirements.txt']
