---
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.5
    hooks:
      - id: ruff
        args: ['--fix']
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.5
    hooks:
      - id: ruff-format
  - repo: https://github.com/python-poetry/poetry
    rev: 1.8.2
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
        args: ['-f', 'requirements.txt', '--without-hashes', '--without', 'dev,docs', '--output', 'requirements.txt']
      - id: poetry-export
        args: ['-f', 'requirements.txt', '--without-hashes', '--with', 'dev,docs', '--output', 'requirements-dev.txt']
