# Project information
site_name: juicenet
site_author: Ravencentric
site_description: CLI tool designed to simplify the process of uploading files to Usenet

# Repository
repo_name: juicenet-cli
repo_url: https://github.com/Ravencentric/juicenet-cli
edit_uri: edit/main/docs/

theme:
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye
  name: material
  favicon: assets/logo.png
  logo: assets/logo.png
  font:
    text: Noto Sans
  palette:
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - navigation.instant
    - navigation.tracking
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - content.action.edit
    - content.action.view
    - content.code.copy
    - content.code.annotate
  plugins:
    - search
    - mkdocstrings:
        enabled: true
        default_handler: python
        handlers:
          python:
            paths: [src]
            options:
              docstring_style: numpy

markdown_extensions:
  - md_in_html
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      url_download: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home: index.md
  - Installation:
      - Local: installation/local.md
      - Docker: installation/docker.md
  - Configuration: configuration.md
  - CLI Reference: cli-reference.md
  - API Reference: api-reference.md
  - Config Files for Nyuu: nyuu-config-files.md
  - Archive:
      - Uploading to Usenet: archive/uploading-to-usenet.md
      - ParPar filepath formats: archive/parpar-filepath-formats.md
