[tool.poetry]
name = "juicenet"
version = "0.6.2"
description = "Crude CLI tool to upload files to Usenet using Nyuu and ParPar"
authors = ["Raventric <78981416+Ravencentric@users.noreply.github.com>"]
license = "Unlicense"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
PyYAML = "^6.0.1"
alive-progress = "^3.1.4"
loguru = "^0.7.2"
rich = "^13.6.0"
rich-argparse = "^1.3.0"

[tool.poetry.group.dev.dependencies]
black = "^23.9.1"

[tool.black]
line-length = 120

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
