# All paths here reflect the inside of the container. These must
# be identical to the container paths passed in docker-compose.yml
NYUU_CONFIG_PRIVATE: /config/nyuu.docker.private.json
NYUU_CONFIG_PUBLIC: /config/nyuu.docker.public.json
NZB_OUTPUT_PATH: /data/nzbs
APPDATA_DIR_PATH: /data/appdata
