# Required Settings
# Do not quote your paths. Paste them as is
PARPAR: C:\Users\user\bin\parpar.exe
NYUU: C:\Users\user\bin\nyuu.exe

# https://juicenet.in/nyuu-config-files/
NYUU_CONFIG_PRIVATE: C:\Users\user\nyuu\config-private.json

# Optional Setting (Remove '#' to specify)
# If NYUU_CONFIG_PUBLIC is undefined, the script will fall back to using the private config
# NYUU_CONFIG_PUBLIC: C:\Users\user\nyuu\config-public.json

NZB_OUTPUT_PATH: D:\output\nzbs
EXTENSIONS: ["mkv", "epub", "cbr", "cbz", "cb7", "cbt"]

# Use %Temp% on Windows or /tmp on POSIX for temporary files.
# Setting it to False will generate temporary files right next to the input files
USE_TEMP_DIR: True

# Optional Setting (Remove '#' to specify)
# TEMP_DIR_PATH requires USE_TEMP_DIR to be True. This just lets you specify a directory where the temp
# files will be generated. Not much reason to use this.
# TEMP_DIR_PATH: D:\output\par

# Optional Setting (Remove '#' to specify)
# This is where juicenet will store persisting data (currently resume data)
# Defaults to ~/.juicenet/
# APPDATA_DIR_PATH: C:\Users\user\.juicenet

# Advanced Setting (Only modify if you know what you're doing)
# Do NOT pass -o, --filepath-format, and --filepath-base. They are handled by the script.
PARPAR_ARGS: ["--overwrite", "-s700k", "--slice-size-multiple=700K", "--max-input-slices=4000", "-r1n*1.2", "-R"]
