# Do not quote your paths. Paste them as is
PARPAR: C:\Users\user\bin\parpar.exe
NYUU: C:\Users\user\bin\nyuu.exe

# https://juicenet.ravencentric.cc/nyuu-config-files/
NYUU_CONFIG_PRIVATE: C:\Users\user\nyuu\config-private.json

NZB_OUTPUT_PATH: D:\output\nzbs
EXTENSIONS: ["mkv", "epub", "cbr", "cbz", "cb7", "cbt"]

# Use %Temp% on Windows or /tmp on Unix for temporary files.
# Setting it to False will generate temporary files right next to the input files
USE_TEMP_DIR: True

# Advanced Setting (Only modify if you know what you're doing)
# Do NOT pass -o, --filepath-format, and --filepath-base. They are handled by the script.
PARPAR_ARGS: ["--overwrite", "-s700k", "--slice-size-multiple=700K", "--max-input-slices=4000", "-r1n*1.2", "-R"]
