name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  release:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: pipx install poetry

      - name: Build project for distribution
        run: poetry build

      - uses: actions/upload-artifact@v3
        with:
          path: "dist/*"
